CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS fraud_scores (
  transaction_id UUID PRIMARY KEY,
  score DOUBLE PRECISION NOT NULL,
  fraud_flag INTEGER NOT NULL,
  scored_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);